name: ditonton
version: 1.0.0+1
publish_to: none
description: A new Flutter application.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  provider: ^6.0.3
  dartz: ^0.10.0-nullsafety.2
  equatable: ^2.0.2
  google_fonts: ^3.0.1
  flutter_rating_bar: ^4.0.0
  cached_network_image: ^3.0.0
  get_it: ^7.1.3
  sqflite: ^2.0.0+3
  path_provider: ^2.0.2
  flutter_bloc: 8.1.1
  firebase_core: 1.21.1
  firebase_analytics: ^9.3.3
  firebase_crashlytics: ^2.8.9
  flutter: 
    sdk: flutter

dev_dependencies: 
  mockito: ^5.0.8
  build_runner: ^2.0.4
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - assets/certificates/
  uses-material-design: true

